services:
  frontend:
    ports:
      - "3000:3000"
    volumes:
      - ../financial-tracker-frontend:/app
    command: npm start
    environment:
      - NODE_ENV=development
  backend:
    ports:
      - "8080:8080"
    volumes:
      - ../financial-tracker-backend:/app
    command: ./mvnw spring-boot:run
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/devdb
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
  etl:
    environment:
      KAFKA_BROKER: kafka:9093
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: devdb
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
  db:
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: devdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: devsecret 