services:
  frontend:
    build:
      context: ../financial-tracker-frontend
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ../financial-tracker-frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8080  # Points to local backend
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: ["sh", "-c", "echo 'REACT_APP_API_URL: $REACT_APP_API_URL'; npm start"]
    networks:
      - fintrack-network
  etl:
    build:
      context: ../financial-tracker-etl
    environment:
      KAFKA_BROKER: ${KAFKA_BROKER}
      DATABASE_HOST: db
      DATABASE_PORT: ${DATABASE_INTERNAL_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_SCHEMA_NAME: ${DATABASE_SCHEMA_NAME}
      # Development-specific Python settings
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
      # Development-specific application settings
      DEBUG: 1
      RELOAD: 1
      # Kafka consumer settings
      KAFKA_CONSUMER_GROUP_ID: etl-job-consumer-group
      KAFKA_CONSUMER_AUTO_OFFSET_RESET: earliest
      KAFKA_CONSUMER_MAX_POLL_INTERVAL_MS: 300000
      KAFKA_CONSUMER_SESSION_TIMEOUT_MS: 60000
      KAFKA_CONSUMER_HEARTBEAT_INTERVAL_MS: 20000
    volumes:
      - ../financial-tracker-etl:/app
    command: ["sh", "-c", "chmod 755 /app/entrypoint.sh; dos2unix /app/entrypoint.sh; /app/entrypoint.sh"]
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_healthy
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "supervisorctl status kafka_consumer | grep RUNNING || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - fintrack-network
  db:
    image: postgres:17.5
    ports:
      - "${DATABASE_HOST_PORT}:${DATABASE_INTERNAL_PORT}"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - fintrack-network
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "${SMTP_PORT}:${SMTP_PORT}" # SMTP server
      - "${MAILHOG_PORT}:${MAILHOG_PORT}" # Web UI
    environment:
      MH_HOSTNAME: ${SMTP_HOST}
      MH_SMTP_BIND_ADDR: 0.0.0.0:1025
      MH_API_BIND_ADDR: 0.0.0.0:8025
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "1025"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - fintrack-network 

  valkey:
    image: valkey/valkey:latest
    ports:
      - "${VALKEY_PORT:-6379}:6379"
    volumes:
      - valkey_data:/data
    command: >
      valkey-server 
      --appendonly yes 
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
      --save 900 1
      --save 300 10
      --save 60 10000
      --bind 0.0.0.0
      --protected-mode no
    environment:
      - VALKEY_LOGLEVEL=${VALKEY_LOGLEVEL:-notice}
    networks:
      - fintrack-network
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  postgres_data:
  valkey_data: 