services:
  frontend:
    ports:
      - "3000:3000"
    volumes:
      - ../financial-tracker-frontend:/app
    command: npm start
    environment:
      - NODE_ENV=development
  backend:
    ports:
      - "8080:8080"
    volumes:
      - ../financial-tracker-backend:/app
    command: ./mvnw spring-boot:run
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:${DATABASE_INTERNAL_PORT}/${DATABASE_NAME}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
  etl:
    environment:
      KAFKA_BROKER: kafka:9093
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_INTERNAL_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
  db:
    ports:
      - "${DATABASE_HOST_PORT}:${DATABASE_INTERNAL_PORT}"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 