version: '3.8'
services:
  jenkins:
    build:
      context: .
      dockerfile: ci-cd/Dockerfile.jenkins
    ports:
      - "9090:8080" # Jenkins UI
      # - "50000:50000" # Optional: Only needed for Jenkins agents
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - JENKINS_OPTS=--httpPort=8080
    user: root  # Start as root to set permissions
    group_add:
      - docker
    restart: unless-stopped
volumes:
  jenkins_home: