version: '3.8'
services:
  jenkins:
    build:
      context: .
      dockerfile: ci-cd/Dockerfile.jenkins
    ports:
      - "9090:8080" # Map Jenkins HTTP to port 9090
      - "50000:50000" # Optional: Only needed for Jenkins agents
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # Mount Docker socket for Jenkins to use Docker
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - JENKINS_OPTS=--httpPort=8080
    restart: unless-stopped
    user: root # Run Jenkins as root to access Docker
volumes:
  jenkins_home: