services:
  frontend:
    ports:
      - "80:80"
    command: ["nginx", "-g", "daemon off;"]
    environment:
      - NODE_ENV=production
  backend:
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/proddb
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
  etl:
    environment:
      KAFKA_BROKER: kafka:9093
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: proddb
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
  db:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: proddb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: prodsecret
    volumes:
      - pgdata:/var/lib/postgresql/data 