apiVersion: apps/v1
kind: Deployment
metadata:
  name: financial-tracker-backend
  namespace: financial-tracker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: financial-tracker-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: ${spring.datasource.url}
        - name: SPRING_DATASOURCE_USERNAME
          value: ${spring.datasource.username}
        - name: SPRING_DATASOURCE_PASSWORD
          value: ${spring.datasource.password}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: financial-tracker-frontend
  namespace: financial-tracker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: financial-tracker-frontend:latest
        ports:
        - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: financial-tracker-db
  namespace: financial-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "fintrack"
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_PASSWORD
          value: "admin"