apiVersion: apps/v1
kind: Deployment
metadata:
  name: fintrack-etl
  labels:
    app: fintrack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fintrack
      component: etl
  template:
    metadata:
      labels:
        app: fintrack
        component: etl
    spec:
      containers:
      - name: etl
        image: your-docker-repo/fintrack-etl:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: ${spring.datasource.url}
        - name: SPRING_DATASOURCE_USERNAME
          value: ${spring.datasource.username}
        - name: SPRING_DATASOURCE_PASSWORD
          value: ${spring.datasource.password}
        volumeMounts:
        - name: etl-data
          mountPath: /data
      volumes:
      - name: etl-data
        emptyDir: {}