pipeline {
    agent any

    stages {
        stage('Clone') {
            steps {
                script {
                    // Clone backend repository
                    echo 'Cloning backend repository...'
                    dir('backend') {
                        git branch: 'main', url: 'https://github.com/fintrack-project/financial-tracker-backend.git'
                    }
                    echo 'Backend repository cloned.'

                    // Clone frontend repository
                    echo 'Cloning frontend repository...'
                    dir('frontend') {
                        git branch: 'main', url: 'https://github.com/fintrack-project/financial-tracker-frontend.git'
                    }
                    echo 'Frontend repository cloned.'

                    // Clone ETL repository
                    echo 'Cloning ETL repository...'
                    dir('etl') {
                        git branch: 'main', url: 'https://github.com/fintrack-project/financial-tracker-etl.git'
                    }
                    echo 'ETL repository cloned.'
                }
            }
        }

        stage('Build') {
            steps {
                script {
                    // Build backend
                    dir('backend') {
                        echo 'Building backend...'
                        sh 'mvn clean package -Dmaven.compiler.source=18 -Dmaven.compiler.target=18'
                        echo 'Backend build completed.'
                    }
                    // Build frontend
                    dir('frontend') {
                        echo 'Building frontend...'
                        sh 'npm install'
                        sh 'npm run build'
                        echo 'Frontend build completed.'
                    }
                    // Setup ETL
                    dir('etl') {
                        echo 'Setting up ETL environment...'
                        sh 'python3 -m venv venv'
                        sh '. venv/bin/activate && pip install -r requirements.txt'
                        echo 'ETL setup completed.'
                    }
                }
            }
        }

        stage('Test') {
            steps {
                echo 'Testing...'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying...'
            }
        }
    }
}